s = set()
n = input("enter your number 1 : ")
s.add(int(n))
n = input("enter your number 2 : ")
s.add(int(n))
n = input("enter your number 3 : ")
s.add(int(n))
n = input("enter your number 4 : ")
s.add(int(n))
n = input("enter your number 5 : ")
s.add(int(n))
n = input("enter your number 6 : ")
s.add(int(n))
n = input("enter your number 7 : ")
s.add(int(n))
n = input("enter your number 8 : ")
s.add(int(n))

print(s)